/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8weDeXT4DOa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui_old/avatar"
import { Card } from "@/components/ui_old/card"

export function persona_overview_dashboard_card() {
  return (
    <Card className="w-full max-w-4xl mx-auto p-6">
      <div className="grid grid-cols-2 gap-4 items-center">
        <div className="space-y-2">
          <h2 className="text-lg font-semibold">Persona Coverage</h2>
          <div className="text-4xl font-bold">25%</div>
          <p className="text-lg">Of Customer Base</p>
        </div>
        <div className="flex flex-col items-center space-y-2 border-l pl-4">
          <Avatar className="w-24 h-24">
            <AvatarImage src="/placeholder-user.jpg" alt="Trendsetter Tara" />
            <AvatarFallback>TT</AvatarFallback>
          </Avatar>
          <div className="text-center">
            <h3 className="text-lg font-semibold">Trendsetter Tara</h3>
            <p className="text-muted-foreground">Persona: Tech-Savvy Enthusiast</p>
          </div>
        </div>
      </div>
      <div className="mt-4 border-t pt-6 flex items-center justify-between">
        <a href="#" className="text-primary flex items-center space-x-1">
          <span>View details</span>
          <ArrowRightIcon className="w-4 h-4" />
        </a>
      </div>
    </Card>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
