/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cdLf4tchTNP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"
import Link from "next/link"

export function persona_overview_card() {
  return (
    <Card className="max-w-md mx-auto p-6">
      <CardContent className="text-center">
        <Avatar className="mx-auto mb-4">
          <AvatarImage src="/placeholder-user.jpg" alt="Busy Becca" />
          <AvatarFallback>BB</AvatarFallback>
        </Avatar>
        <h2 className="text-xl font-semibold">Busy Becca</h2>
        <p className="text-muted-foreground">Persona: Busy Parent</p>
      </CardContent>
      <CardContent className="border-t pt-4 p-10">
        <div className="space-y-4">
          <div>
            <h3 className="text-sm font-semibold text-muted-foreground pb-2">PRIMARY GOAL</h3>
            <p className="text-sm">• Find reliable, family friendly products</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-muted-foreground pb-2">KEY CHALLENGE</h3>
            <p className="text-sm">• Concern about product safety and durability</p>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-muted-foreground pb-2">MAIN BUYING MOTIVATION</h3>
            <p className="text-sm">• Finding the best multipurpose/multifunctional product</p>
          </div>
        </div>
      </CardContent>
      <Separator className="my-4" />
      <CardFooter className="pt-4">
        <Link href="#" className="inline-flex items-center text-black" prefetch={false}>
          View details <ArrowRightIcon className="ml-2 h-4 w-4 text-black" />
        </Link>
      </CardFooter>
    </Card>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
