/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xo166G5Wo0T
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function persona_details_card() {
  return (
    <div className="max-w-sm mx-auto bg-white rounded-lg shadow-md overflow-hidden">
      <img
        src="/placeholder.svg"
        alt="Profile"
        className="w-full h-auto"
        width="300"
        height="300"
        style={{ aspectRatio: "300/300", objectFit: "cover" }}
      />
      <div className="p-4">
        <h2 className="text-xl font-bold font-inter">Frugal Francesca</h2>
        <p className="text-muted-foreground font-inter">Cost-Conscious Consumer</p>
        <hr className="my-4" />
        <div className="space-y-2">
          <div>
            <h3 className="text-sm font-semibold text-muted-foreground font-inter">PRIMARY GOAL</h3>
            <div className="mt-2">
              <p className="font-inter">Save money on daily expenses.</p>
            </div>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-muted-foreground font-inter">KEY CHALLENGE</h3>
            <div className="mt-2">
              <p className="font-inter">Balancing quality with cost.</p>
            </div>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-muted-foreground font-inter">MAIN BUYING MOTIVATION</h3>
            <div className="mt-2">
              <p className="font-inter">Finding the best deals and discounts.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
