/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oNZ2T1FCzBZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function sidenav() {
  return (
    <div className="flex flex-col w-64 min-h-screen bg-white shadow-lg">
      <div className="flex items-center justify-center h-16 bg-primary">
        <img
          src="/placeholder.svg"
          alt="Logo"
          className="h-10"
          width="40"
          height="40"
          style={{ aspectRatio: "40/40", objectFit: "cover" }}
        />
        <span className="ml-2 text-2xl font-bold text-white">Interseed</span>
      </div>
      <div className="p-4 pt-6 mt-4">
        <div className="flex items-center mb-6 space-x-2">
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select Workspace" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="workspace1">Workspace 1</SelectItem>
              <SelectItem value="workspace2">Workspace 2</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="outline" size="icon">
            <PlusIcon className="w-4 h-4" />
          </Button>
        </div>
        <nav className="space-y-2">
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-gray-700 rounded-md hover:bg-gray-100"
            prefetch={false}
          >
            <HomeIcon className="w-5 h-5" />
            <span>Create Persona</span>
          </Link>
          <Link
            href="#"
            className="flex items-center p-2 space-x-2 text-gray-700 bg-secondary rounded-md hover:bg-secondary-foreground"
            prefetch={false}
          >
            <BookmarkIcon className="w-5 h-5" />
            <span>View Personas</span>
            <div className="ml-auto">
              <ChevronRightIcon className="w-4 h-4" />
            </div>
          </Link>
          <div className="pl-8 space-y-2">
            <Link
              href="#"
              className="flex items-center p-2 space-x-2 text-gray-700 rounded-md hover:bg-gray-100"
              prefetch={false}
            >
              <ClipboardIcon className="w-5 h-5" />
              <span>Persona Insights</span>
            </Link>
            <Link
              href="#"
              className="flex items-center p-2 space-x-2 text-gray-700 rounded-md hover:bg-gray-100"
              prefetch={false}
            >
              <ActivityIcon className="w-5 h-5" />
              <span>Persona Analytics</span>
            </Link>
          </div>
        </nav>
      </div>
    </div>
  )
}

function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
    </svg>
  )
}


function BookmarkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
